name: Siesta test page

markdown: kramdown

##permalink: /blog/:year/:month/:day/:title

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

#baseurl: "/web-portal"
baseurl: "/leem/siesta-jekyll"
#
material_baseurl: "/leem/SIESTA_MATERIAL"


